# debugMode enables / disables the debug mode for Rasa and Rasa X
debugMode: true
nginx:
  service:
    enabled: true
    # connect LoadBalancer directly to VMs' internal IP
    # You get this value with: $ hostname -I
    externalIPs: [35.188.219.145]

rasax:
    # initialUser is the user which is created upon the initial start of Rasa X
    initialUser:
        # password for the Rasa X user
        password: "aSecureRandomString"
    # passwordSalt Rasa X uses to salt the user passwords
    passwordSalt: "AnotherSecureRandomString"
    # token Rasa X accepts as authentication token from other Rasa services
    token: "AnotherSecureRandomString"
    # jwtSecret which is used to sign the jwtTokens of the users
    jwtSecret: "AnotherSecureRandomString"
    # tag refers to the Rasa X image tag
    tag: "1.1.4"
rasa:
    # token Rasa accepts as authentication token from other Rasa services
    token: "AnotherSecureRandomString"
    # tag refers to the Rasa image tag
    tag: "3.1.7-full"
    additionalChannelCredentials:
        rest:
        socketio:
            user_message_evt: user_uttered
            bot_message_evt: bot_uttered
            session_persistence: true/false
    versions:
        rasaProduction:
            enabled: true
            #replicaCount: 2
        rasaWorker:
            enabled: true
rabbitmq:
    # rabbitmq settings of the subchart
    rabbitmq:
        # password which is used for the authentication
        password: "AnotherSecureRandomString"
    auth:
        erlangCookie: "AnotherSecureRandomString"
global:
    # postgresql: global settings of the postgresql subchart
    postgresql:
        # postgresqlPassword is the password which is used when the postgresqlUsername equals "postgres"
        postgresqlPassword: "AnotherSecureRandomString"
    # redis: global settings of the postgresql subchart
    redis:
        # password to use in case there no external secret was provided
        password: "AnotherSecureRandomString"
